### ISSUE TITLE
Graf za shiny

### ISSUE THREAD

**Issue by sabrinacalcina** [sabrinacalcina/APPR-2019-20#4]
Pri ustvarjanju Shiny grafa sem naletela na težave in sicer ne dela mi funkcija za graf: graf_aktivnost v analiza_sabrina.R  in ne vem zakaj. Prosila bi če lahko malo pogledate, hvala.

**Comment by katarinabrilej** [comment]
Graf lahko izrišeš neposredno v Shiny-ju, ni ti treba prej pisati funkcije in filtrirati, ker lahko narediš tako 
```
aktivnost <- aktivnost %>% filter(spol==input$spol &
                                      starostna_skupina ==input$starostna_skupina  & input$meritve)
```
Torej neposredno filtriraš glede na to katera možnost je izbrana v Shiny-ju.
Tu mora biti `starostna_skupina` namesto `Starost` in `meritve` namesto `Meritev` (ker je tako v tabeli aktivnost). 
Prav tako moraš v datoteki `ui.R` spremeniti možni izbiri za spol, ti sta Moški in Ženske.
Zdi se mi tudi, da moraš pri uvozu tabele aktivnost dodati še `fileEncoding="Windows-1250"`, saj vsaj meni sicer ne prebere šumnikov.

**Comment by sabrinacalcina** [comment]
Sem poskusila nekaj spremeniti in sicer sem poskusila brez funkcije, ampak mi ševedno nekaj ne dela. Prosila bi, če lahko pogledate ali sem sploh šla v pravo smer s spremembami.

**Comment by katarinabrilej** [comment]
Poleg tega, da filtriraš tabelo `aktivnost` moraš v shiny kodo dodati še prejšnjo kodo iz funkcije, ki potem graf dejansko izriše.
```
 don <- xts(x=aktivnost$leto, order.by=as.yearqtr.default(aktivnost$delovno_sposobni))
   dygraph(don) %>%
     dyOptions(labelsUTC = TRUE, fillGraph=TRUE, fillAlpha=0.1, 
               drawGrid = FALSE, colors="#f09ce0") %>%
     dyCrosshair(direction = "vertical") %>%
     dyHighlight(highlightCircleSize = 5, highlightSeriesBackgroundAlpha = 0.2, 
                 hideOnMouseOut = FALSE)  %>%
     dyRoller(rollPeriod = 1) %>%
     dySeries("V1", label = "Število")
```

**Comment by katarinabrilej** [comment]
Vidim, da si pri tabeli `aktivnost` spremenila encoding, naredi tako tudi pri ostalih tabelah, ker v podatkih nastopajo šumniki.
