### ISSUE TITLE
Letnice

### ISSUE THREAD

**Issue by sabrinacalcina** [sabrinacalcina/APPR-2019-20#5]
Pri svoji projektni imam še 2 problema in sicer pri grafu "Brezposelnost na 1000 prebivalcev glede na čas iskanja dela" mi noče izpisati šumnikov v naslovu grafa(kljub temu, da sem dodala fileEncoding="Windows-1250"), pri ostalih grafih pa to ni bil problem.
Ter pri zadnjem grafu 
"Delovno sposobni glede na aktivnost in mere aktivnosti po starostnih skupinah in spolu za celotno Slovenijo"
ne znam narediti take skale v x osi da bi mi vse letnice prikazalo ne pa samo 2010, kar tudi ni bil problem pri ostalih grafih, vendar le pri temu.
Kako naj odpravim težave?

**Comment by katarinabrilej** [comment]
V grafu `Brezposelnost na 1000 prebivalcev glede na čas iskanja dela` meni normalno izpiše šumnike v naslovu, je pa potrebno popraviti `col=čas` namesto `col=cas`. Raje pa kar popravi stolpec `čas` v tabeli `trajanje`, saj se v imenih stolpcev izogibamo šumnikov. Potem ti ni treba v grafu nič spreminjati.

**Comment by katarinabrilej** [comment]
Če tako popraviš,  prikaže vsako drugo letnico. (`don` ne spreminjaš s funkcijo `xts` ampak samo izluščiš podatke za leto in število delovno sposobnih)
```
shinyServer(
  function(input, output) {
    output$aktivnost <- renderDygraph({ 
      aktivnost <- aktivnost %>% filter(spol == input$spol & 
                                          starostna_skupina == input$starostna_skupina & meritve == input$meritve)
      don <- aktivnost[,c("leto","delovno_sposobni")]
      dygraph(don) %>% dyOptions(labelsUTC = TRUE, fillGraph=TRUE, fillAlpha=0.1, drawGrid = TRUE, colors="#2FFFFF	") %>%
        dyCrosshair(direction = "vertical") %>%
        dyHighlight(highlightCircleSize = 4, highlightSeriesBackgroundAlpha = 0.2, hideOnMouseOut = FALSE)  %>%
        dyRoller(rollPeriod = 1) %>%
        dySeries("delovno_sposobni", label = "Število") 
    })
    
  })
```

**Comment by katarinabrilej** [comment]
Vidim tudi, da še nisi spremenila povezave za binder, tako da prosim to naredi (je odprt issue na to temo).
